### ISSUE TITLE
User not marked offline after backgriunding

### ISSUE THREAD

**Issue by reghrafa** [smilefam/SendBird-SDK-dotNET#5]
When an app enters into the background the SendBird SDK does not detect the change in the applications state. Therefore, the user is still marked online and no push notifications are sent.

**Comment by sf-harry-kim** [comment]
Sorry for the inconvenience.

Due to the platform limitation we don't currently support auto connecting/disconnecting feature on our Unity SDK.

But you can still call disconnect/connect method explicitly when your app goes to background or vice versa.

If you would like to check that currently offline or online, please check out this method on Unity SDK.

https://docs.sendbird.com/ref/dotnet/class_send_bird_1_1_send_bird_client.html#af69d268e7e50cfc8a71ce96ab28762a9

We recommend that you should call disconnect before going to background to receive push notification because push notifications only be sent to offline users.
